# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import raft_pb2 as raft__pb2


class RaftStub(object):
  """Raft gRPC implementation
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestVote = channel.unary_unary(
        '/Raft/RequestVote',
        request_serializer=raft__pb2.VoteRequest.SerializeToString,
        response_deserializer=raft__pb2.Ack.FromString,
        )
    self.AppendEntries = channel.unary_unary(
        '/Raft/AppendEntries',
        request_serializer=raft__pb2.Entries.SerializeToString,
        response_deserializer=raft__pb2.Ack.FromString,
        )
    self.ReceivePropose = channel.unary_unary(
        '/Raft/ReceivePropose',
        request_serializer=raft__pb2.Proposal.SerializeToString,
        response_deserializer=raft__pb2.Ack.FromString,
        )


class RaftServicer(object):
  """Raft gRPC implementation
  """

  def RequestVote(self, request, context):
    """Takes an ID (use shared IDKey message type) and returns k nodes with
    distance closest to ID requested
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AppendEntries(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReceivePropose(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RaftServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestVote': grpc.unary_unary_rpc_method_handler(
          servicer.RequestVote,
          request_deserializer=raft__pb2.VoteRequest.FromString,
          response_serializer=raft__pb2.Ack.SerializeToString,
      ),
      'AppendEntries': grpc.unary_unary_rpc_method_handler(
          servicer.AppendEntries,
          request_deserializer=raft__pb2.Entries.FromString,
          response_serializer=raft__pb2.Ack.SerializeToString,
      ),
      'ReceivePropose': grpc.unary_unary_rpc_method_handler(
          servicer.ReceivePropose,
          request_deserializer=raft__pb2.Proposal.FromString,
          response_serializer=raft__pb2.Ack.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Raft', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
